# QRZ Login - callsign lookup source
qrz_callsign = ""
qrz_password = ""
# HamQTH Login - callsign lookup source
hamqth_callsign = ""
hamqth_password = ""
# QTH Location (use degrees)
latitude = ""
longitude = ""
# Dark Sky API Key - weather
darksky_api_key = ""
